name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted]
    env:
      WORKSPACE : ${{github.workspace}}
      http_proxy : http://proxy-chain.intel.com:911
      https_proxy : http://proxy-chain.intel.com:912
    steps:
      - run: echo "Get started"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "hello world"

