name: Xiphos integration CI
on:
  pull_request:
    types:
      - opened
    branches:
      - 'xiphos-integration'
      - 'master'

jobs:
  build_docker:
      runs-on: [self-hosted]
      outputs:
          image_name: localhost:5000/gazelle-jni-ci-image:latest
      steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: docker build -t localhost:5000/gazelle-jni-ci-image:latest  tools/dockers/build_docker
      - run: docker push localhost:5000/gazelle-jni-ci-image:latest

  build:
    runs-on: [self-hosted]
    needs: build_docker
    container: 
      image: ${{needs.build_docker.outputs.image_name}}
    env:
      WORKSPACE : ${{github.workspace}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: jfrog/setup-jfrog-cli@v2
      - run: jfrog --version
      - run: tools/build_gazelle_jni.sh
      - run: tools/run_tests.sh

